### ISSUE TITLE
Payment gateways

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1540]
- [ ] Support payments with PayPal #704 
- [ ] Add support for Adyen payments #1349 
- [ ] Implement Mercado Pago #1654
