### ISSUE TITLE
Introduce guest checkout

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1762]
Needs #1744 

When ordering, visitors shouldn't be forced to register, it should become optional. 
We still need to ask them their phone number & full name, to be able to fulfill the delivery. 
Even if the email validation step disappears, we should however at least check that the email is valid, and does not use a throwable email service. 

At the end of the checkout, it should be suggested that they register, to find their previous orders. 

[Some interesting patterns](https://www.userzoom.com/blog/11-interesting-approaches-to-guest-checkout-design/)

**TODO**

- [x] Redirect to a "public" order page instead of a profile page after checkout success (6e455b4fb848f1fa226d92b771314e7ad664612d)
- [x] Add message to suggest registering after checkout is complete (94fe066e7fa39b634454160f000e10b8289226e4)
- [x] Don't allow guest checkout if a user with same email already exists (854cce5de18fdbac89ed95ceae73ade0bbcb1d5b)
- [x] Allow using LoopEat without an account (store credentials at customer level) (a2a9350bc007049e368ecf8c3d90d4ffbe93d2de)
- [ ] Don't allow disposable emails (use https://www.validator.pizza/)
- [ ] Clear LoopEat credentials after guest checkout to avoid impersonating a customer
- [ ] Show terms & conditions checkbox for guest checkout
