### ISSUE TITLE
Introduce multi step deliveries

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#2610]
Right now, even if a `Delivery` object is actually a collection of `Task` objects, we often assume that it has only 2 tasks, a pickup and a dropoff. 

The goal is to allow managing "multi step" deliveries, i.e for example a pickup and 5 dropoffs. 

### PHP API

**Deprecating the getPickup() and getDropoff() methods**

The `getPickup()` and `getDropoff()` methods can't be fully removed, but their usage should be reduced. 

To stay BC:
- The `getPickup()` method will return the **first** pickup
- The `getDropoff()` method will return the **last** dropoff (if multiple dropoffs)

**The distance of a delivery**

Right now, the `distance` of a `Delivery` is the distance between the pickup and the dropoff. 
With multiple steps, it will be the same, i.e the computed distance of all tasks. 

**TODO**

- [x] In `CancelTasks` reactor, use `Delivery::getTasks()`
- [x] In `RoutingInterface::getDistance()` calls, use `Delivery::getTasks()`
- [x] In `DeliveryType`, use a dynamic collection of forms with `items`, instead of `pickup`/`dropoff` (#2612)
- [ ] Modify `getPickup()`/`getDropoff()` implementations
- [ ] Modify `addTask()` implementation to allow adding more than 2 tasks

---

### HTTP API

To maintain BC, the API will still return the `pickup` and `dropoff` props. A new `items` prop will be added. 

**BEFORE**
```json
{
  "pickup": {},
  "dropoff": {}
}
```

**AFTER**
```json
{
  "pickup": {},
  "dropoff": {},
  "items": [
    {}, 
    {}
  ]
}
```

**Comment by AdrienSICKLO** [comment]
@alexsegura this can be closed?

**Comment by alexsegura** [comment]
@AdrienSICKLO it's already closed 🙂
