### ISSUE TITLE
In order to lay a foundation for incident reporting, as an administrator I want a order / task history 

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3686]
**In order to**  `achieve something`
For any individual task I want a history of the task with all its modifications (assigning, delaying, created, modified...) and a page that shows these events in a timeline. To do this we need to

- [ ] create the ability to register information associated with the task at its creation differently once it is modified (see when the original delivery time range was even after being delayed by a restaurant)
- [ ] create a page where a task history can be seen (not just in the admin panel task modal)

**As a** `role`
Everyone

**I want** `something to be added or changed`
To do this we need to

- [ ] create the ability to register information associated with the task at its creation differently once it is modified (see when the original delivery time range was even after being delayed by a restaurant)
- [ ] create a page where a task history can be seen (not just in the admin panel task modal)
- [ ] We also then want these task histories to be combined together for linked tasks (like an order), which will have its own history page with the actions taken on all the tasks associated with that order

**Whereas currently** `this happens`
We only have the admin dashboard history and the activity page

**Additional context**
This is developing more this existing feature
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/2cf8d587-8340-4e7e-afb3-f219957cb5d7)

**Comment by alexsegura** [comment]
Currently, the events that happened to an order aren't displayed anywhere on the platform. 
What is displayed on the orders dashboard in cards, is the timeline of events (pickup, preparation, dropoff) that have been calculated by the platform, not the actual events that happened after that. 

So, maybe one first step would be to show the "real" timeline of events in order cards, alongside with the timeline that is currently displayed.

**Comment by Paul-Eraman-CoopCycle** [comment]
In some places it is shown, the live information I mean. In the tasks in the administration panel in the more info space above, plus in the activity page. But like so many things,the information is both incomplete and separated into various places without too much coherence.

**Comment by Paul-Eraman-CoopCycle** [comment]
This history should be able to have comments, like mentioned in the issue https://github.com/coopcycle/coopcycle-web/issues/2799

**Comment by Paul-Eraman-CoopCycle** [comment]
This should be available in the incidents review page we are discussion @r0xsh

**Comment by Paul-Eraman-CoopCycle** [comment]
This has been developed in the incident details page antoine has made, so i'm going to call this closed. in the future we can readress putting it in the task modal in the dashboard
