### ISSUE TITLE
Rush mode

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#422]
The order preparation time is now calculated depending on the order total. 
We need to introduce another variable: the restaurant should be able to indicate it is currently in a rush. 
In "rush" mode, order preparation times are increased. 

Also, we should allow the owner to close temporarily the restaurant (until the next opening date, for example)

**TODO**

- [x] Add a field in restaurant to specify mode 192fe848a5019763e2b5412da8fac337d39e63d7
- [x] Add an API endpoint to switch mode 63de92f429e121b4b468eb63c496fcacdf6ab618
- [x] Take rush mode into account in preparation time calculation 8ea21f1099898c86e498d703cb24697f7c2d3cb6
- [x] Add an API endpoint to close temporarily the restaurant (= add a closing rule) 4e11fe06c03d74abac704a1baa7f1a6c10c2432b
