### ISSUE TITLE
Refactor order API endpoints

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#423]
Order API endpoints should be refactored. 

**TODO**

- [x] Add functional tests for all endpoints (accept, refuse, cancel)
- [x] Make sure the user performing the action is authorized
- [ ] ~Stop using action classes, use EventSubsribers for correct error serialization & API docs~ 
- [x] Use the "controller" key for action classes for correct error serialization & API docs

Also see [API Platform docs about security](https://api-platform.com/docs/core/security/#security)

**Comment by alexsegura** [comment]
Fixed in 9aa9a9d20579ea9583dd547f79b04f5f1c5b6ad6
