### ISSUE TITLE
Rename "doneBefore" & "doneAfter" to "before" & "after"

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#535]
The name of those properties does not make sense, they shouldn't be in the past. 

https://github.com/coopcycle/coopcycle-web/blob/60cdddefbecfae4149748d1a86d9e9a4018346b6/src/AppBundle/Entity/Task.php#L121-L130

**TODO**

- [ ] Accept `before` & `after` in [`TaskNormalizer::denormalize`](https://github.com/coopcycle/coopcycle-web/blob/60cdddefbecfae4149748d1a86d9e9a4018346b6/src/AppBundle/Serializer/TaskNormalizer.php#L83)
- [ ] Add test for POST payload
- [ ] Also serialize `before` & `after` in [`TaskNormalizer::normalize`](https://github.com/coopcycle/coopcycle-web/blob/60cdddefbecfae4149748d1a86d9e9a4018346b6/src/AppBundle/Serializer/TaskNormalizer.php#L22)
- [ ] Rename database fields & class methods

**Comment by ERAMANrepartos** [comment]
@alexsegura This is done right?
